### ISSUE TITLE
Block Reward Restructure - Reducing Block Reward due to high Inflation Rate

### ISSUE THREAD

**Issue by Sonofotis** [oxen-io/oxen-improvement-proposals#30]
# Introduction
At the start of Oxen's inception I was tasked with helping develop the token economics of the Service Node layer, this resulted in multiple economic papers and a great monetary policy to create sybil resistance network. I'd like to revisit the tokeneconomics of Oxen now that we are years into it's life and aim to create a more sound economic model into the future.

The current Oxen Block Reward is 18.333 per block which creates a yearly inflation rate of ~9%, this in turn means each Oxen will lose ~9% of it's purchasing power over the next year. The inflation rate in my opinion is the only metric that is letting the Oxen network down in regards to token economics, which is where most of my focus will be for this proposal.

It is in our best interest for the network to reduce the inflation rate as much as possible as this in turn:
- reduces the purchasing power lost per Oxen per year
- reduces the sell side pressure on the market

We need to keep in mind that the inflation rate directly relates to the rewards service node operators receive so we need the inflation rate high enough to incentivise a service node to operate.

I understand that a Service Node operator may initially think "Reducing the rewards!? This isn't in my best interest" however they may not realise that their rewards are losing purchasing power by the inflation rate on the token and thus they are already experiencing this reduction. 

# AIM
Ideally we should be aiming for the lowest inflation rate possible while maintaining a high enough ROI to incentivise SN operators. My target's for this proposal will be the following:
|Goal           | Target            | Reasoning |
|----------------|--------------------|---------|
| Inflation Rate | As low as possible |Reduce selling pressure and loss of purchasing power|
| ROI(in Oxen)   | Greater than 8%    | Incentivise Service Nodes to operate|

Having the ROI in Oxen greater than 8% will continue to keep an incentive for Service Node's to come onto the network.
Reducing the inflation rate as low as possible will increase the dollar value of each Oxen through time.

# Assumptions
Cryptocurrency token economics is complicated especially with so many moving parts so reducing the complexity is key to gathering any quick insights. 

A lot of the complexity comes from variables that are dynamic and that change based on market conditions such as the dollar value of each Oxen and the number of Service Nodes active at any given point. 

### Lock up Ratio
The lock up ratio measures how much of the supply is locked into Service Nodes. The higher the lock up ratio the more sybil resistant the network is.
A lock up ratio of 50% is ideal as a 100% lock up means no Oxen is available to be used and a Lock up ratio of 0% means no Service Node operators.
To reduce the complexity of the problem an assumed **Lock up ratio of 50%** is set for this study.

### Demand
We will assume the **demand for Oxen is static** and that the demand for Oxen matches the sell side pressure therefore assuming that the price of Oxen does not change. 

This assumption reduces the complexity drastically however in reality demand fluctuates. Reducing the block reward allows for a lower demand to maintain price.

### Dollar value of Oxen
To reduce the complexity of the problem we will assume the **price of Oxen to not change** and only measure ROI in Oxen, rather than dollars. 

Keep in mind that inflation rate reduces purchasing power of each Oxen and if demand does not meet emission the price of Oxen will fall. This is why one of the aims of the proposal is to decrease the inflation rate as much as possible.

# Data
The following graphs depict 3 case studies where the only variable we change is the Block Reward.
| Case                   | Block Reward  |
|------------------------|---------------|
| 1. Current             | 18.33333 Oxen |
| 2. 25% reduction in BR | 13.75 Oxen    |
| 3. 50% reduction in BR | 9.17 Oxen     |
## Circulating Supply
Circulating supply was calculated by adding the block reward for 3 different case studies. This data was used to generate Fig 2 and 3.

The circulating supply data does not give us any insights into if we should make the proposed changes however it is the basis to work out the Inflation Rates.
![circ](https://user-images.githubusercontent.com/39609800/119077408-93c41180-ba37-11eb-981a-5807f7039616.jpg)
*Figure 1. Circulating Supply*

## Yearly inflation Rate
In this chart the inflation rate seems way to high and will continue to be high for several years into the future. In the current schedule our inflation rate is 9% and will only drop below 5% in the year 2030.

We desire an inflation rate that is the lowest possible however we need to look into what reducing the emission does to the ROI and make a decision based on the two graphs.

![ir](https://user-images.githubusercontent.com/39609800/119085842-d42b8b80-ba47-11eb-848d-0e30ffb84183.jpg)
*Figure 2. Inflation Rate*

## Return on Investment

The return on investment is calculated from the 15,000 Oxen staked, the block reward and the number of service nodes on the network at each given point. One major assumption for this graph is that SN count increases through time and the network maintains a 50% lockup.

As you can see the Inflation rate chart(Fig 2) and the ROI chart (Fig 3) are near identical, this is because as you reduce the emission, the inflation is reduced but the ROI is also reduced. 
![ROI](https://user-images.githubusercontent.com/39609800/119077414-958dd500-ba37-11eb-8970-3f5884bad20d.jpg)
*Figure 3. Return on Investment measured in Oxen where the lock up ratio stays at 50%*

# Proposal
After reviewing both the ROI and Inflation Rate charts in my opinion a block reward reduction of 25% to create a static BR of 13.75 Oxen will create better economic conditions for the longevity of the project. 

# Other considerations
### Reducing block reward may cause initial decommissions
Reducing the block reward may result in an initial reduction in Service Node operators as each operator has a different threshold of ROI that they prefer. 
This is counteracted by two scenarios.
1. As Service Nodes leave the network the ROI is increased per service node as they have a larger share of the overall network.
2. The reduction in rewards also results in a reduction of inflation rate, thus increasing the potential for each Oxen they hold to go up in value. 

### Operating expenses
This study does not take into consideration the operating expenses of running a Service Node. 
I chose to remove this from the study as it costs approximately $10 per month to run a node. The rewards in dollar value greatly outweighs this cost and I found this portion of the study to be negligible. The only time this would become to much of an issue is if the price of Oxen drops drastically however by reducing the emission we assume that Oxen has better conditions to go up in value rather than down.

**Comment by darcys22** [comment]
+1 For this

**Comment by Prophet-26** [comment]
I am completely against further reducing the block reward. #Sub 12% ROI is not attractive in the context of crypto and I would not consider operating my service nodes at that return. 

Instead of punching in some code and reducing the block reward as a band-aid measure, more effort should be made in offsetting the inflation with the proposed burning programmes. 

Saying the current inflation rate is "the only metric that is letting the Oxen network down in regards to token economics" is wildly naive. There are other highly successful project with much higher inflation rates - most notable THORChain.

**Comment by KeeJef** [comment]
In my view emissions have no relationship to Service Node ROI, Service Node ROI is determined by the market and whether new people want to start nodes at the current rate of return. Keep in mind the Service Node count has been continually increasing at about the same rate since we started the network. People keep starting new nodes so clearly we haven't reached a point where Service Node ROI has reached equilibrium. 

Emission's do have a direct relationship with the size of the Service Node network, the less reward the less overall Service Nodes are required before there are too many nodes sharing the same rewards and ROI compresses to equilibrium. So the question in my view is, how many Service Nodes do we need? and what level of rewards is required to reach that number of nodes before equilibrium is reached.  

I don't really have answers to those questions because that depends on network usage (Lokinet/Session usage) and what other market participants consider a good enough ROI to start new Service Nodes.

**Comment by jagerman** [comment]
> this in turn means each Oxen will lose ~9% of it's purchasing power over the next year

Respectfully disagree with this.  Purchasing power is determined by *price* inflation rather than *money supply* inflation and the two are only loosely linked.

Essentially this makes an assumption that Oxen's market cap will remain fixed over time, but that in itself is not merely an unreasonable assumption, but in fact a self-contradictory one: *if* everyone believed that that was true then Oxen would have no speculative demand, and that in turn would tank the price, thus *changing* the market cap and violating the assumption.

Case in point: from 1y ago to today, price went from $0.32 to $1.16, that's price *deflation* of 72%.  Or from 2y ago to 1y ago: deflation of 58%.

The point is: the coin emission rate has a very small impact on the price (and the price *is* purchasing power), which means tweaking it is only going to have a very small impact on anything.

> Keep in mind the Service Node count has been continually increasing at about the same rate since we started the network.

That *was* true up until about 2 months ago, but then the pattern broke: SN counts went substantially above trend just after the Chainflip airdrop announcement because that airdrop effective increased the ROI from staking service nodes.

In terms of ROI, there is already a *huge* reduction in SN ROI looming on the horizon on June 30th.

> I understand that a Service Node operator may initially think "Reducing the rewards!? This isn't in my best interest" however they may not realise that their rewards are losing purchasing power by the inflation rate on the token and thus they are already experiencing this reduction.

This is a bit misleading as written: SN stakers would still be unequivocally negatively impacted by a reduction in SN rewards; the conjectured reduction in price inflation offsets this a bit, but not entirely.  For example: if SN stakers are earning 9% (nominally) of the total supply and have 50% stake lockup, this means they are earning 18% on their investment.  If price inflation just happens to equal coin emission inflation then that means in real terms (i.e. after adjusting for price inflation) they are earning 9%: 18% nominal minus 9% price inflation.

If you reduce emission to 6% of circulating supply, then 50% staked earns 12% ROI nominally, and that works out to 6% real -- and so in real terms, you reduced the SN return by one-third.

Effectively SN stakers earn all of the new coins, but only incur 50% of the inflation cost of new emissions (since any resulting inflation is borne by *all* OXEN holders, of which SN stakers are only 50%).  And because of that, any cut to SN rewards *will* hurt SN stakers even under an assumption that emission inflation = price inflation.

Or another way to look at it: *any* SN reward is a transfer in value from non-staking holders to staking holders, and any reduction in SN reward is tilting things back the other way.  There's no *correct* tradeoff here, but we need to be clear that *any* change in the SN reward emission is about making one party better off at the expense of the other.

**Comment by jagerman** [comment]
I'll also add: I think we should be extremely hesitant about changing the emissions schedule, in general.  Sometimes changes *are* justified, but I think our bar for justifying such a change should be high, and I'm not seeing a strong enough justification here.
